# Generated by Django 4.2.6 on 2024-04-24 21:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clipboard',
            fields=[
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=5000)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
